### ISSUE TITLE
commons-cli chokes on '-' characters

### ISSUE THREAD

**Issue by dmacvicar** [asual/lesscss-engine#60]
```
java -classpath /usr/share/java/commons-logging.jar:/usr/share/java/commons-cli.jar:/usr/share/java/lesscss-engine.jar:/usr/share/java/rhino.jar com.asual.lesscss.LessEngineCli spacewalk.less

Exception in thread "main" java.lang.IllegalArgumentException: opt contains illegal character value '-'
        at org.apache.commons.cli.OptionValidator.validateOption(OptionValidator.java:73)
        at org.apache.commons.cli.Option.<init>(Option.java:123)
        at org.apache.commons.cli.Options.addOption(Options.java:131)
        at org.apache.commons.cli.Options.addOption(Options.java:114)
        at com.asual.lesscss.LessEngineCli.main(LessEngineCli.java:49)
```

It works if all options defined in LessOptions.java that contains '-' are camelcased.

**Comment by jasonsperske** [comment]
Just ran in to this bug (I'm running 1.5.1 with commons-cli 1.2)

**Comment by veve90** [comment]
Me too...
