### ISSUE TITLE
Caused by: com.asual.lesscss.LessException: java.net.MalformedURLException: unknown protocol: jndi

### ISSUE THREAD

**Issue by asherri** [asual/lesscss-engine#67]
I'm using jboss to run web app,
this library throws this exception:
Caused by: com.asual.lesscss.LessException: java.net.MalformedURLException: unknown protocol: jndi
	at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:252)
	at com.asual.lesscss.LessEngine.compile(LessEngine.java:180)
	at com.asual.lesscss.LessEngine.compile(LessEngine.java:165)
	at com.my.system.frontend.LessCssGen.generateCssFromLess(LessCssGen.java:49)

**Comment by prtng** [comment]
@asherri : I am using Tomcat. I get the below exception if one of my less file contains `@import`. Exception:
```
Caused by: com.asual.lesscss.LessException: org.mozilla.javascript.UniqueTag@4c1a61e0: NOT_FOUND Error: java.net.MalformedURLException: unknown protocol: jndi (line -1, column -1)
    at com.asual.lesscss.LessEngine.parseLessException(LessEngine.java:249)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:140)
    at com.asual.lesscss.LessEngine.compile(LessEngine.java:123)
```

Was the issue you mentioned resolved?
